hello/hello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("goodbye/", include("goodbye.urls")),
    path("todos/", include("todos.urls")),
    path("users/", include("users.urls")),
    path("api/", include('todos.api.urls')),
]

hello/todos/api/urls.py
from django.conf.urls import url, include
from .views import TodosViewSet, EmployeeInfoViewSet, UserViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('employeeinfo', EmployeeInfoViewSet, basename='employeeinfo')
router.register('todos', TodosViewSet, basename='todos')
router.register('users', UserViewSet, basename='users')
urlpatterns = [
    url('', include(router.urls))
]

hello/todos/urls.py
from django.urls import path, include
from . import views

# avoids namespace collusion for many apps
app_name = "todos"

urlpatterns = [
    path("", views.TodosListView.as_view(), name="index"),
    path("add", views.add, name="add"),
    path("<id>/", views.task_detail, name="detail"),
    path("pdf", views.cv_to_pdf, name="to_pdf"),
]

hello/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout")
]

hello/todos/models.py
from django.db import models

# Create your models here.
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Person(models.Model):
    id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=100, null=True, default="awel")
    lastname = models.CharField(max_length=100, null=True, default="eshetu")

    def __str__(self):
        return f"{self.firstname} : {self.lastname}"


class EmployeeInfo(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    brief_exprience = models.TextField(max_length=500, null=True, blank=True)


class Todos(models.Model):
    id = models.AutoField(primary_key=True)
    task = models.CharField(max_length=100)
    day = models.CharField(max_length=100)
    time = models.CharField(max_length=100)
    # relate Todos with Person table and delete todos related to persons when a person is deleted
    person = models.ForeignKey(
        EmployeeInfo, on_delete=models.CASCADE, related_name="persons"
    )

    def __str__(self):
        return f"You have '{self.task}' on '{self.day}' at '{self.time}' assigned to '{self.person}'."
        
    def calculate_product(self, x, y):
        return x*y

class LessID(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    description = models.TextField(max_length=300, null=True, blank=True)

hello/todos/api/views.py
from todos.models import Todos, EmployeeInfo
from django.contrib.auth.models import User
from rest_framework import viewsets, permissions
from .serializers import TodosSerializer, EmployeeInfoSerializer, UserSerializer

# EmployeInfo Viewset 

class EmployeeInfoViewSet(viewsets.ModelViewSet):
    queryset = EmployeeInfo.objects.all()
    permission_classes = [
        permissions.AllowAny
    ]
    serializer_class = EmployeeInfoSerializer

#Todos Viewset

class  TodosViewSet(viewsets.ModelViewSet):
    queryset = Todos.objects.all()
    permission_classes = [
        permissions.AllowAny
    ]
    serializer_class = TodosSerializer

#User Viewset

class  UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    permission_classes = [
        permissions.AllowAny
    ]
    serializer_class = UserSerializer

hello/todos/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Todos, Person, EmployeeInfo
from django.contrib.auth.models import User
from django.views.generic import DetailView, ListView
# Create your views here.
from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile

# create form and validate it
class TodosForm(forms.Form):
    user = forms.CharField(label='User')
    email = forms.EmailField(label='Email')
    title = forms.CharField(label='Title')
    experience =forms.CharField(widget=forms.Textarea, label='Experience')
    task = forms.CharField(label="Task")
    day = forms.CharField(label="Day")
    time = forms.CharField(label="Time")

class TodosListView(ListView):
    model = Todos
    template_name = 'todos/index.html'
    context_object_name = 'tasks'
    
    def get_context_data(self, *kwargs):
        context = super().get_context_data(*kwargs)
        emplyees = EmployeeInfo.objects.all()
        context['employees'] = emplyees
        return context

    def calculate_sum(self, x, y):
        return x+y
    
def add(request):
    # check if the form is has valid data and save it to tasks array, if not send back the add form
    # if request is not post, initialize an empty form
    form = TodosForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            task = form.cleaned_data["task"]
            day = form.cleaned_data["day"]
            time = form.cleaned_data["time"]
            user = form.cleaned_data['user']
            email = form.cleaned_data['email']
            title = form.cleaned_data['title']
            experience = form.cleaned_data['experience'] # very funny look in the UI
            u=User(username=user, email=email)
            u.save()
            p = EmployeeInfo(user=u, title=title, brief_exprience=experience)
            p.save()
            t = Todos(task=task, day=day, time=time, person=p)
            t.save()
            # after adding a task redirect to the task list page
            return HttpResponseRedirect(reverse("todos:index"))
        else:
            return render(request, "todos/add.html", {"form": form})

    return render(request, "todos/add.html", {"form": TodosForm()})


def task_detail(request, id):
    # pk a must to have abaove
    # task.persons.all() -> will get all persons related to the task ( persons <- mentioned as related name in the models)
    task = Todos.objects.get(id=id)

    return render(
        request,
        "todos/task_detail.html",
        {
            "task": task,
        },
    )


def cv_to_pdf(request):
    """Generate pdf."""
    # Model data
    print(f'the request object coming is {request}')
    
    task = {"task": "hello", "day": "monday", "time": "wholeday"}

    # Rendered
    html_string = render_to_string("todos/task_detail.html", {"task": task})
    html = HTML(string=html_string)
    result = html.write_pdf()

    # Creating http response
    response = HttpResponse(content_type="application/pdf;")
    response["Content-Disposition"] = "inline; filename=list_people.pdf"
    response["Content-Transfer-Encoding"] = "binary"
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, "rb")
        response.write(output.read())

    return response

hello/todos/templates/todos/add.html
{% extends "todos/layout.html" %}

    {% block todos %}
            <h1>Add Your Tasks</h1>
            <form class="addtask" action="{% url 'todos:add' %}" method="post">
                {% csrf_token %} <!--must have for cross communications sercurity reasons/ if not csrf middleware in the sitting.py won't allow form submission-->
             {{ form }} <!---form created and validated in the views.TodosForm-->
            <input type="submit" value="Submit" />
            </form>
           <a href="{% url 'todos:index' %}">View Tasks</a>
    {% endblock %}

hello/todos/templates/todos/index.html
    {% extends "todos/layout.html" %}
    {% load static i18n %}
    {% block todos %}
    
            <h1>Your Tasks</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                {% if user %}
                 <li class="nav-item">Welcome, {{user }}</li>
                 {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Log Out</a></li>
            </ul>
        </div>
    </nav> 
    <table
    id="table"
    data-toggle="table"
    data-toolbar="#toolbar"
    data-search="true"
    data-sort-class="table-active"
    data-sortable="true">
    <caption>Weekly Todos</caption>
    <thead>
        <tr>
        <th data-sortable="true">{% trans "Task" %}</th>
        <th data-sortable="true">{% trans "Day" %}</th>
        <th data-sortable="true">{% trans "Time" %}</th>
        <th data-sortable="true">{% trans "Name" %}</th>
        <th data-sortable="true">{% trans "Email" %}</th>
        <th data-sortable="true">{% trans "Title" %}</th>
        <th data-sortable="true">{% trans "Exprience rief" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td> <a href="{% url 'todos:detail' task.id %}">{{task.task}}</a></td>
            <td> {{ task.day }}</td>
            <td> {{ task.time }}</td>
            <td>{{task.person.user.username}}</td>
            <td> {{task.person.user.email}}</td>
            <td> {{task.person.title}}</td>
            <td> {{task.person.brief_exprience}}</td>
        </tr>
        {% empty %}
        <tr>
            <td>
                No tasks.
            </td>
        </tr>
        {% endfor %}    
    </tbody>
    </table>
    <div><a href="{% url 'todos:add' %}">Add Task</a></div> 
    {% endblock %}

    

hello/todos/templates/todos/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="{% static 'todos/styles.css' %}" rel="stylesheet">
    <title>Good bye</title>
  </head>
  <body>
    {% block todos %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"></script>
  </body>
</html>

hello/todos/templates/todos/task_detail.html
{% extends "todos/layout.html" %}
{% block todos %}
<h1>Task id : {{task.id}}</h1>
<ul>
    <li>Task name : {{task.task}}</li>
    <li>Day : {{task.day}}</li>
    <li>Time : {{task.time}}</li>

</ul>
<a href="{% url 'todos:index' %}">Back</a>
<a href="{% url 'todos:to_pdf' %}">Print</a>
{% endblock %}